from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from ..fetchers.base import Signal
from .llm import call_json, load_prompt

SYSTEM_ZH = "你是 DailyDawn 主笔，技术派独立开发者观察员。严格输出 JSON，不要解释。"
SYSTEM_EN = "You are the DailyDawn editor-in-chief. Output strict JSON only; no commentary."

# 章节标题按语言本地化
SECTION_TITLES = {
    "zh": {
        "top3": "📍 今日 Top 3 信号",
        "high_confidence": "高置信度",
        "external_find": "外部发现",
        "double_validation": "双重验证",
        "opener": "🗣 主编视角",
        "build_2h": "🎯 今日构建",
        "launch": "机会发现",
        "tech": "技术选型",
        "competition": "竞争情报",
        "demand": "需求雷达",
        "trend": "趋势观察",
        "action_header": "🔥 本周行动",
        "action_weekend": "周末扩展构建",
        "action_this_week": "这一周更长线的赌注",
        "action_risk": "本周最大的风险 / 陷阱",
        "footer": "由 DailyDawn 自动生成",
    },
    "en": {
        "top3": "📍 Top 3 signals today",
        "high_confidence": "High confidence",
        "external_find": "External find",
        "double_validation": "Double validation",
        "opener": "🗣 Editor's take",
        "build_2h": "🎯 Today's build",
        "launch": "Launch discoveries",
        "tech": "Tech stack",
        "competition": "Competitive intel",
        "demand": "Demand radar",
        "trend": "Trend watch",
        "action_header": "🔥 This week's actions",
        "action_weekend": "Weekend extension build",
        "action_this_week": "This week's longer bet",
        "action_risk": "Biggest risk / trap this week",
        "footer": "Auto-generated by DailyDawn",
    },
}

# 按顺序渲染的 expert bucket
_EXPERT_ORDER = ("launch", "tech", "competition", "demand", "trend")


def _strip_bullet_prefix(text: str) -> str:
    """去掉开头可能重复的 bullet 标记，避免模板拼接出现 '- - xxx'。"""
    return re.sub(r"^\s*[-*•]\s*", "", text or "").strip()


def _format_signal_brief(s: Signal) -> dict:
    return {
        "source": s.source,
        "title": s.title,
        "url": s.url,
        "raw_score": s.raw_score,
        "comments": s.comments,
        "author": s.author,
        "published_at": s.published_at,
    }


def _summarize_expert(markdown: str, max_chars: int = 800) -> str:
    """把专家段落压缩到前 max_chars（editor 只用它提炼 Top 3 和 build，不需全文）。"""
    if not markdown:
        return ""
    stripped = markdown.strip()
    return stripped if len(stripped) <= max_chars else stripped[:max_chars] + "..."


# ======================================================================
# Post-LLM 时间描述一致性校验
# ----------------------------------------------------------------------
# LLM 即使加了 prompt 约束仍会偶发生成：
#   1) 时间叠词病句："过去 2 天前" / "in the past 2 days ago"
#   2) h3 标题与正文时间描述矛盾："今天发布的 X" + 正文"X 在 2 天前发布"
# 这层 post-processing 用正则做兜底，不重试 LLM（避免 pipeline 耗时翻倍）
# ======================================================================

_TIME_STUTTER_ZH = re.compile(r"过去\s*(\d+)\s*(天|小时|日|周)\s*前")
_TIME_STUTTER_EN = re.compile(
    r"\b(?:in|over)\s+the\s+past\s+(\d+)\s+(day|days|hour|hours|week|weeks)\s+ago\b",
    re.IGNORECASE,
)

# h3 里暗示"今日发布"的措辞
_H3_TODAY_ZH = re.compile(r"(今天|今日)(发布|上线|推出|开源|登场|首发)")
_H3_TODAY_EN = re.compile(
    r"\b(released|launched|shipped|announced|dropped|debuted)\s+today\b",
    re.IGNORECASE,
)

# 正文里明确"非今天"的时间描述
_DAYS_AGO_ZH = re.compile(r"\d+\s*天前|过去\s*\d+\s*天(?!前)")
_DAYS_AGO_EN = re.compile(
    r"\b\d+\s+days?\s+ago\b|\b(?:in|over)\s+the\s+past\s+\d+\s+days\b",
    re.IGNORECASE,
)

_EN_TODAY_DOWNGRADE = {
    "released today": "recently released",
    "launched today": "recently launched",
    "shipped today": "recently shipped",
    "announced today": "recently announced",
    "dropped today": "recently dropped",
    "debuted today": "recently debuted",
}

# **关键判断** 与 **反向视角** 之间的分隔修复：
# LLM 经常把两者 inline 挤成一段（"...。 **反向视角**：..."）或仅用单换行。
# GitHub markdown 和 RSS 阅读器不走 Web 层 CSS，源 markdown 必须是空行分隔
# 的独立段落才会正确换行渲染。
# 用零宽度前瞻保留 "**反向视角**" 本身，只把前面的空白/换行替换为 \n\n。
# [^\n]+? 非贪婪且不跨行：LLM 输出的这两段基本是单行结论，跨多行是极端情况，
# 跨行时正则不命中，原样保留，不破坏结构。
_SPLIT_VERDICT_COUNTER_ZH = re.compile(
    r"(\*\*关键判断\*\*[：:][^\n]+?)\s*(?=\*\*反向视角\*\*)"
)
_SPLIT_VERDICT_COUNTER_EN = re.compile(
    r"(\*\*Key call\*\*[:：][^\n]+?)\s*(?=\*\*Counterpoint\*\*)",
    re.IGNORECASE,
)

# 🔍 信号段内多条目必须硬换行（每行末两个空格 + 换行）。LLM 常把 3 个条目用
# "；" 或 ";" inline 串联，GitHub / RSS / 邮件渲染会挤成一坨。
# 段落边界：从 "**🔍 信号**" 或 "**🔍 Signal**" 开始，到下一个空行（\n\n）或文末止
_SIGNAL_PARA_ZH = re.compile(
    r"(\*\*\s*🔍?\s*信号\s*\*\*[：:][\s\S]*?)(?=\n\n|\Z)"
)
_SIGNAL_PARA_EN = re.compile(
    r"(\*\*\s*🔍?\s*Signal\s*\*\*[:：][\s\S]*?)(?=\n\n|\Z)",
    re.IGNORECASE,
)
# 条目分隔符：; 或 ； 紧跟 "[" 链接开头
_SIGNAL_ITEM_SEP = re.compile(r"[;；]\s*(?=\[)")


def _fix_time_stutter(markdown: str, lang: str) -> str:
    """修时间叠词：过去 N 天前 → N 天前；in the past N days ago → N days ago"""
    if lang == "zh":
        return _TIME_STUTTER_ZH.sub(r"\1 \2前", markdown)
    return _TIME_STUTTER_EN.sub(r"\1 \2 ago", markdown)


def _split_verdict_counter(markdown: str, lang: str) -> str:
    """
    强制 **关键判断** 与 **反向视角** 之间为 \\n\\n（独立段落）。
    幂等：已经正确分隔的会原样保留。
    """
    pat = _SPLIT_VERDICT_COUNTER_ZH if lang == "zh" else _SPLIT_VERDICT_COUNTER_EN
    return pat.sub(r"\1\n\n", markdown)


def _split_signal_items(markdown: str, lang: str) -> str:
    """
    🔍 信号段内的多条目用 markdown 硬换行（行尾两空格 + \\n）拆成独立行。
    仅在信号段内替换 "；[" / ";[" 为 "  \\n["，其他段落的分号不动。
    """
    para_pat = _SIGNAL_PARA_ZH if lang == "zh" else _SIGNAL_PARA_EN

    def _rewrite(m: re.Match) -> str:
        return _SIGNAL_ITEM_SEP.sub("  \n", m.group(1))

    return para_pat.sub(_rewrite, markdown)


def _downgrade_h3_today(h3_line: str, lang: str) -> str:
    """把 h3 里"今天发布 X" / "released today" 降级为"最近发布 X" / "recently released"。"""
    if lang == "zh":
        # 只替换首次出现的"今天"/"今日"，降低误伤
        return re.sub(r"今天|今日", "最近", h3_line, count=1)
    out = h3_line
    for old, new in _EN_TODAY_DOWNGRADE.items():
        out = re.sub(re.escape(old), new, out, count=1, flags=re.IGNORECASE)
    return out


def _validate_time_consistency(markdown: str, lang: str) -> str:
    """
    扫描每个 h3 section。如果 h3 含"今天发布 X"类措辞，而同节正文明确出现
    "N 天前"或"past N days"描述，判定为标题-正文时间矛盾，把 h3 降级为"最近发布"。

    保守启发式：正文时间词可能指向其他主体（误伤低概率），但对 VoxCPM2 / GLM-5.1
    这类 h3 + 正文同主体幻觉的命中率高，值得做。
    """
    today_pat = _H3_TODAY_ZH if lang == "zh" else _H3_TODAY_EN
    days_ago_pat = _DAYS_AGO_ZH if lang == "zh" else _DAYS_AGO_EN

    lines = markdown.split("\n")
    # 收集 h3 起始行号；追加 sentinel 方便取 section body
    h3_indices = [i for i, ln in enumerate(lines) if ln.startswith("### ")]
    h3_indices.append(len(lines))

    for k in range(len(h3_indices) - 1):
        start = h3_indices[k]
        end = h3_indices[k + 1]
        h3 = lines[start]
        if not today_pat.search(h3):
            continue
        body = "\n".join(lines[start + 1 : end])
        if not days_ago_pat.search(body):
            continue
        # 冲突：降级 h3 措辞
        lines[start] = _downgrade_h3_today(h3, lang)

    return "\n".join(lines)


def _call_editor_json(
    *,
    lang: str,
    date: str,
    priority_signals: list[Signal],
    cross_themes: list[dict],
    trends: list[Signal],
    experts_output: list[dict],
) -> dict:
    template = load_prompt(f"editor.{lang}.md")

    experts_summary = {
        e["bucket"]: _summarize_expert(e.get("markdown", ""))
        for e in experts_output
    }

    user = (
        template
        .replace("{{date}}", date)
        .replace(
            "{{cross_themes}}",
            json.dumps(cross_themes, ensure_ascii=False, indent=2),
        )
        .replace(
            "{{priority_signals}}",
            json.dumps(
                [_format_signal_brief(s) for s in priority_signals[:10]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{trends_data}}",
            json.dumps(
                # 全量传入（<= 30 条，pytrends 预设 20 关键词过滤后通常 <15）
                [_format_signal_brief(t) for t in trends[:30]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{experts_summary}}",
            json.dumps(experts_summary, ensure_ascii=False, indent=2),
        )
    )

    system = SYSTEM_ZH if lang == "zh" else SYSTEM_EN
    return call_json(system, user, temperature=0.55)


def _assemble_markdown(
    *,
    lang: str,
    date: str,
    editor_output: dict,
    experts_output: list[dict],
) -> str:
    """
    Python 端模板拼接最终 markdown。结构：

        # DailyDawn · YYYY-MM-DD
        > Top 3 信号（引用块视觉突出）
        ---
        ## 技术派说（开篇 POV 600-800 字）
        ## 今日 2 小时构建
        ---
        ## 发现机会   (expert)
        ## 技术选型   (expert)
        ## 竞争情报   (expert)
        ## 需求雷达   (expert)
        ## 趋势判断   (expert)
        ---
        ## 行动触发
        ### 周末扩展构建
        ### 这一周更长线的赌注
        ### 本周最大的风险 / 陷阱
        ---
        _footer_
    """
    t = SECTION_TITLES[lang]
    expert_by_bucket = {
        e["bucket"]: (e.get("markdown") or "").strip() for e in experts_output
    }

    top = editor_output.get("top_signals", {}) or {}
    opener = (editor_output.get("opener") or "").strip()
    builds = editor_output.get("builds", {}) or {}
    today_2h = (builds.get("today_2h") or "").strip()
    weekend = (builds.get("weekend") or "").strip()
    this_week = (builds.get("this_week") or "").strip()
    risk = (builds.get("risk") or "").strip()

    high_conf = _strip_bullet_prefix(top.get("high_confidence", "—"))
    ext_find = _strip_bullet_prefix(top.get("external_find", "—"))
    double_val = _strip_bullet_prefix(top.get("double_validation", "—"))

    timestamp = datetime.now(timezone.utc).isoformat()

    parts: list[str] = [
        f"# DailyDawn · {date}",
        "",
        # Top 3 前置到开篇（引用块视觉突出）
        f"> **{t['top3']}**",
        ">",
        f"> 1. **{t['high_confidence']}**：{high_conf}",
        f"> 2. **{t['external_find']}**：{ext_find}",
        f"> 3. **{t['double_validation']}**：{double_val}",
        "",
        "---",
        "",
        f"## {t['opener']}",
        "",
        opener or "_（今日 POV 开篇生成失败）_",
        "",
        f"## {t['build_2h']}",
        "",
        today_2h or "_（今日构建点子生成失败）_",
        "",
        "---",
        "",
    ]

    for bucket in _EXPERT_ORDER:
        title = t[bucket]
        body = expert_by_bucket.get(bucket, "") or f"_（{title} 段落生成失败）_"
        parts.extend([f"## {title}", "", body, ""])

    parts.extend([
        "---",
        "",
        f"## {t['action_header']}",
        "",
        f"### {t['action_weekend']}",
        "",
        weekend or "_（周末延伸建议生成失败）_",
        "",
        f"### {t['action_this_week']}",
        "",
        this_week or "_（本周长线赌注生成失败）_",
        "",
        f"### {t['action_risk']}",
        "",
        risk or "_（本周风险提示生成失败）_",
        "",
        "---",
        "",
        # 包成 <time datetime> 标签：Web 层 BaseLayout 的 JS 会扫描并渲染为浏览器本地时间
        f'_{t["footer"]} · <time datetime="{timestamp}">{timestamp}</time>_',
    ])

    return "\n".join(parts)


def run_editor(
    *,
    lang: str,
    date: str,
    signals: list[Signal],
    classification: dict,
    experts_output: list[dict],
    trends: list[Signal],
) -> str:
    """
    主笔 agent：产出开篇 + Top 3 + 三级构建 + 风险（JSON）；
    Python 端把 5 个专家段落原文拼接到最终 markdown。
    """
    cross_themes = classification.get("cross_source_themes", [])
    priority_ids = classification.get("priority_ids", [])
    priority_signals = [
        signals[i] for i in priority_ids if 0 <= i < len(signals)
    ]

    try:
        editor_output = _call_editor_json(
            lang=lang,
            date=date,
            priority_signals=priority_signals,
            cross_themes=cross_themes,
            trends=trends,
            experts_output=experts_output,
        )
    except Exception as err:
        print(f"[editor:{lang}] failed, falling back to empty skeleton: {err}")
        editor_output = {
            "opener": "",
            "top_signals": {},
            "builds": {},
        }

    markdown = _assemble_markdown(
        lang=lang,
        date=date,
        editor_output=editor_output,
        experts_output=experts_output,
    )

    # Post-LLM 正则修复：
    #   1. 强制关键判断 / 反向视角独立段落（让 GitHub、RSS、邮件渲染都正确换行）
    #   2. 🔍 信号段内多条目硬换行（避免 "；[link]" inline 挤成一段）
    #   3. 修时间叠词病句（"过去 N 天前"）
    #   4. 降级 h3-body 时间矛盾（"今天发布 X" + 正文"N 天前"）
    markdown = _split_verdict_counter(markdown, lang)
    markdown = _split_signal_items(markdown, lang)
    markdown = _fix_time_stutter(markdown, lang)
    markdown = _validate_time_consistency(markdown, lang)

    return markdown
