from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from ..fetchers.base import Signal
from .llm import call_json, load_prompt


def _strip_bullet_prefix(text: str) -> str:
    """去掉开头可能重复的 bullet 标记（- / * / •），避免模板拼接出现 '- - xxx'。"""
    return re.sub(r"^\s*[-*•]\s*", "", text or "").strip()

SYSTEM_ZH = "你是 DailyDawn 主笔，技术派独立开发者观察员。严格输出 JSON，不要解释。"
SYSTEM_EN = "You are the DailyDawn editor-in-chief. Output strict JSON only; no commentary."

# 章节标题按语言本地化
SECTION_TITLES = {
    "zh": {
        "opener": "🗣 技术派说",
        "build": "🎯 今日 2 小时构建",
        "top3": "📍 今日 Top 3 信号",
        "high_confidence": "高置信度",
        "external_find": "外部发现",
        "double_validation": "双重验证",
        "tech": "技术选型",
        "launch": "发现机会",
        "competition": "竞争情报",
        "demand": "需求雷达",
        "footer": "由 DailyDawn 自动生成",
    },
    "en": {
        "opener": "🗣 Editor's take",
        "build": "🎯 Today's 2-hour build",
        "top3": "📍 Top 3 signals today",
        "high_confidence": "High confidence",
        "external_find": "External find",
        "double_validation": "Double validation",
        "tech": "Tech stack",
        "launch": "Launch discoveries",
        "competition": "Competitive intel",
        "demand": "Demand radar",
        "footer": "Auto-generated by DailyDawn",
    },
}


def _format_signal_brief(s: Signal) -> dict:
    """editor 只需精简信号摘要（不含 summary 长文本），减少 input token。"""
    return {
        "source": s.source,
        "title": s.title,
        "url": s.url,
        "raw_score": s.raw_score,
        "comments": s.comments,
        "author": s.author,
    }


def _summarize_expert(markdown: str, max_chars: int = 600) -> str:
    """把专家段落压缩到前 max_chars，给 editor 做 Top 3 提炼用（减少 input token）。"""
    if not markdown:
        return ""
    stripped = markdown.strip()
    return stripped if len(stripped) <= max_chars else stripped[:max_chars] + "..."


def _call_editor_json(
    *,
    lang: str,
    date: str,
    priority_signals: list[Signal],
    cross_themes: list[dict],
    trends: list[Signal],
    experts_output: list[dict],
) -> dict:
    template = load_prompt(f"editor.{lang}.md")

    experts_summary = {
        e["bucket"]: _summarize_expert(e.get("markdown", ""))
        for e in experts_output
    }

    user = (
        template
        .replace("{{date}}", date)
        .replace(
            "{{cross_themes}}",
            json.dumps(cross_themes, ensure_ascii=False, indent=2),
        )
        .replace(
            "{{priority_signals}}",
            json.dumps(
                [_format_signal_brief(s) for s in priority_signals[:10]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{trends_data}}",
            json.dumps(
                [_format_signal_brief(t) for t in trends[:10]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{experts_summary}}",
            json.dumps(experts_summary, ensure_ascii=False, indent=2),
        )
    )

    system = SYSTEM_ZH if lang == "zh" else SYSTEM_EN
    return call_json(system, user, temperature=0.55)


def _assemble_markdown(
    *,
    lang: str,
    date: str,
    editor_output: dict,
    experts_output: list[dict],
) -> str:
    """Python 端模板拼接最终 markdown：开篇 + Top3 + 构建点子 + 4 专家段落 + 尾注。"""
    t = SECTION_TITLES[lang]
    expert_by_bucket = {e["bucket"]: (e.get("markdown") or "").strip() for e in experts_output}

    top = editor_output.get("top_signals", {}) or {}
    opener = (editor_output.get("opener") or "").strip()
    build_idea = (editor_output.get("build_idea") or "").strip()

    high_conf = _strip_bullet_prefix(top.get("high_confidence", "—"))
    ext_find = _strip_bullet_prefix(top.get("external_find", "—"))
    double_val = _strip_bullet_prefix(top.get("double_validation", "—"))

    timestamp = datetime.now(timezone.utc).isoformat()

    parts = [
        f"# DailyDawn · {date}",
        "",
        f"## {t['opener']}",
        "",
        opener or "_（今日 POV 开篇生成失败）_",
        "",
        f"## {t['build']}",
        "",
        build_idea or "_（今日构建点子生成失败）_",
        "",
        f"## {t['top3']}",
        "",
        f"- **{t['high_confidence']}**：{high_conf}",
        f"- **{t['external_find']}**：{ext_find}",
        f"- **{t['double_validation']}**：{double_val}",
        "",
        "---",
        "",
        f"## {t['tech']}",
        "",
        expert_by_bucket.get("tech", "_（技术选型段落生成失败）_"),
        "",
        f"## {t['launch']}",
        "",
        expert_by_bucket.get("launch", "_（发现机会段落生成失败）_"),
        "",
        f"## {t['competition']}",
        "",
        expert_by_bucket.get("competition", "_（竞争情报段落生成失败）_"),
        "",
        f"## {t['demand']}",
        "",
        expert_by_bucket.get("demand", "_（需求雷达段落生成失败）_"),
        "",
        "---",
        "",
        f"_{t['footer']} · {timestamp}_",
    ]
    return "\n".join(parts)


def run_editor(
    *,
    lang: str,
    date: str,
    signals: list[Signal],
    classification: dict,
    experts_output: list[dict],
    trends: list[Signal],
) -> str:
    """
    主笔 agent：只生成开篇 + Top3 + 构建点子（JSON）；
    Python 端把 4 个专家段落原文拼接到最终 markdown。
    """
    cross_themes = classification.get("cross_source_themes", [])
    priority_ids = classification.get("priority_ids", [])
    priority_signals = [
        signals[i] for i in priority_ids if 0 <= i < len(signals)
    ]

    try:
        editor_output = _call_editor_json(
            lang=lang,
            date=date,
            priority_signals=priority_signals,
            cross_themes=cross_themes,
            trends=trends,
            experts_output=experts_output,
        )
    except Exception as err:
        print(f"[editor:{lang}] failed, falling back to empty opener: {err}")
        editor_output = {"opener": "", "build_idea": "", "top_signals": {}}

    return _assemble_markdown(
        lang=lang,
        date=date,
        editor_output=editor_output,
        experts_output=experts_output,
    )
