from __future__ import annotations

import json
import re
from datetime import datetime, timezone

from ..fetchers.base import Signal
from .llm import call_json, load_prompt

SYSTEM_ZH = "你是 DailyDawn 主笔，技术派独立开发者观察员。严格输出 JSON，不要解释。"
SYSTEM_EN = "You are the DailyDawn editor-in-chief. Output strict JSON only; no commentary."

# 章节标题按语言本地化
SECTION_TITLES = {
    "zh": {
        "top3": "📍 今日 Top 3 信号",
        "high_confidence": "高置信度",
        "external_find": "外部发现",
        "double_validation": "双重验证",
        "opener": "🗣 技术派说",
        "build_2h": "🎯 今日 2 小时构建",
        "launch": "发现机会",
        "tech": "技术选型",
        "competition": "竞争情报",
        "demand": "需求雷达",
        "trend": "趋势判断",
        "action_header": "🔥 行动触发",
        "action_weekend": "周末扩展构建",
        "action_this_week": "这一周更长线的赌注",
        "action_risk": "本周最大的风险 / 陷阱",
        "footer": "由 DailyDawn 自动生成",
    },
    "en": {
        "top3": "📍 Top 3 signals today",
        "high_confidence": "High confidence",
        "external_find": "External find",
        "double_validation": "Double validation",
        "opener": "🗣 Editor's take",
        "build_2h": "🎯 Today's 2-hour build",
        "launch": "Launch discoveries",
        "tech": "Tech stack",
        "competition": "Competitive intel",
        "demand": "Demand radar",
        "trend": "Trend verdict",
        "action_header": "🔥 Action triggers",
        "action_weekend": "Weekend extension build",
        "action_this_week": "This week's longer bet",
        "action_risk": "Biggest risk / trap this week",
        "footer": "Auto-generated by DailyDawn",
    },
}

# 按顺序渲染的 expert bucket（对应  章节顺序）
_EXPERT_ORDER = ("launch", "tech", "competition", "demand", "trend")


def _strip_bullet_prefix(text: str) -> str:
    """去掉开头可能重复的 bullet 标记，避免模板拼接出现 '- - xxx'。"""
    return re.sub(r"^\s*[-*•]\s*", "", text or "").strip()


def _format_signal_brief(s: Signal) -> dict:
    return {
        "source": s.source,
        "title": s.title,
        "url": s.url,
        "raw_score": s.raw_score,
        "comments": s.comments,
        "author": s.author,
    }


def _summarize_expert(markdown: str, max_chars: int = 800) -> str:
    """把专家段落压缩到前 max_chars（editor 只用它提炼 Top 3 和 build，不需全文）。"""
    if not markdown:
        return ""
    stripped = markdown.strip()
    return stripped if len(stripped) <= max_chars else stripped[:max_chars] + "..."


def _call_editor_json(
    *,
    lang: str,
    date: str,
    priority_signals: list[Signal],
    cross_themes: list[dict],
    trends: list[Signal],
    experts_output: list[dict],
) -> dict:
    template = load_prompt(f"editor.{lang}.md")

    experts_summary = {
        e["bucket"]: _summarize_expert(e.get("markdown", ""))
        for e in experts_output
    }

    user = (
        template
        .replace("{{date}}", date)
        .replace(
            "{{cross_themes}}",
            json.dumps(cross_themes, ensure_ascii=False, indent=2),
        )
        .replace(
            "{{priority_signals}}",
            json.dumps(
                [_format_signal_brief(s) for s in priority_signals[:10]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{trends_data}}",
            json.dumps(
                [_format_signal_brief(t) for t in trends[:10]],
                ensure_ascii=False,
                indent=2,
            ),
        )
        .replace(
            "{{experts_summary}}",
            json.dumps(experts_summary, ensure_ascii=False, indent=2),
        )
    )

    system = SYSTEM_ZH if lang == "zh" else SYSTEM_EN
    return call_json(system, user, temperature=0.55)


def _assemble_markdown(
    *,
    lang: str,
    date: str,
    editor_output: dict,
    experts_output: list[dict],
) -> str:
    """
    Python 端模板拼接最终 markdown。结构模仿 ：

        # DailyDawn · YYYY-MM-DD
        > Top 3 信号（引用块视觉突出）
        ---
        ## 技术派说（开篇 POV 600-800 字）
        ## 今日 2 小时构建
        ---
        ## 发现机会   (expert)
        ## 技术选型   (expert)
        ## 竞争情报   (expert)
        ## 需求雷达   (expert)
        ## 趋势判断   (expert)
        ---
        ## 行动触发
        ### 周末扩展构建
        ### 这一周更长线的赌注
        ### 本周最大的风险 / 陷阱
        ---
        _footer_
    """
    t = SECTION_TITLES[lang]
    expert_by_bucket = {
        e["bucket"]: (e.get("markdown") or "").strip() for e in experts_output
    }

    top = editor_output.get("top_signals", {}) or {}
    opener = (editor_output.get("opener") or "").strip()
    builds = editor_output.get("builds", {}) or {}
    today_2h = (builds.get("today_2h") or "").strip()
    weekend = (builds.get("weekend") or "").strip()
    this_week = (builds.get("this_week") or "").strip()
    risk = (builds.get("risk") or "").strip()

    high_conf = _strip_bullet_prefix(top.get("high_confidence", "—"))
    ext_find = _strip_bullet_prefix(top.get("external_find", "—"))
    double_val = _strip_bullet_prefix(top.get("double_validation", "—"))

    timestamp = datetime.now(timezone.utc).isoformat()

    parts: list[str] = [
        f"# DailyDawn · {date}",
        "",
        # Top 3 前置到开篇（BP 风格的引用块视觉突出）
        f"> **{t['top3']}**",
        ">",
        f"> 1. **{t['high_confidence']}**：{high_conf}",
        f"> 2. **{t['external_find']}**：{ext_find}",
        f"> 3. **{t['double_validation']}**：{double_val}",
        "",
        "---",
        "",
        f"## {t['opener']}",
        "",
        opener or "_（今日 POV 开篇生成失败）_",
        "",
        f"## {t['build_2h']}",
        "",
        today_2h or "_（今日构建点子生成失败）_",
        "",
        "---",
        "",
    ]

    for bucket in _EXPERT_ORDER:
        title = t[bucket]
        body = expert_by_bucket.get(bucket, "") or f"_（{title} 段落生成失败）_"
        parts.extend([f"## {title}", "", body, ""])

    parts.extend([
        "---",
        "",
        f"## {t['action_header']}",
        "",
        f"### {t['action_weekend']}",
        "",
        weekend or "_（周末延伸建议生成失败）_",
        "",
        f"### {t['action_this_week']}",
        "",
        this_week or "_（本周长线赌注生成失败）_",
        "",
        f"### {t['action_risk']}",
        "",
        risk or "_（本周风险提示生成失败）_",
        "",
        "---",
        "",
        f"_{t['footer']} · {timestamp}_",
    ])

    return "\n".join(parts)


def run_editor(
    *,
    lang: str,
    date: str,
    signals: list[Signal],
    classification: dict,
    experts_output: list[dict],
    trends: list[Signal],
) -> str:
    """
    主笔 agent：产出开篇 + Top 3 + 三级构建 + 风险（JSON）；
    Python 端把 5 个专家段落原文拼接到最终 markdown。
    """
    cross_themes = classification.get("cross_source_themes", [])
    priority_ids = classification.get("priority_ids", [])
    priority_signals = [
        signals[i] for i in priority_ids if 0 <= i < len(signals)
    ]

    try:
        editor_output = _call_editor_json(
            lang=lang,
            date=date,
            priority_signals=priority_signals,
            cross_themes=cross_themes,
            trends=trends,
            experts_output=experts_output,
        )
    except Exception as err:
        print(f"[editor:{lang}] failed, falling back to empty skeleton: {err}")
        editor_output = {
            "opener": "",
            "top_signals": {},
            "builds": {},
        }

    return _assemble_markdown(
        lang=lang,
        date=date,
        editor_output=editor_output,
        experts_output=experts_output,
    )
