from __future__ import annotations

from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).parent.parent


def render_markdown(report: dict, lang: str, date: str) -> str:
    """把 LLM 返回的 JSON 渲染为人类可读的 Markdown。"""
    is_zh = lang == "zh"

    def t(zh: str, en: str) -> str:
        return zh if is_zh else en

    lines: list[str] = []
    lines.append(f"# {t('每日黎明', 'DailyDawn')} · {date}")
    lines.append("")
    summary = report.get("summary", "")
    if summary:
        lines.append(f"> {summary}")
        lines.append("")

    # Top Trends
    lines.append(f"## {t('今日趋势', 'Top Trends')}")
    lines.append("")
    for i, trend in enumerate(report.get("top_trends", []), 1):
        lines.append(f"### {i}. {trend.get('title', '')}")
        lines.append("")
        if trend.get("evidence"):
            lines.append(f"**{t('证据', 'Evidence')}：** {trend['evidence']}")
            lines.append("")
        if trend.get("why_matters"):
            lines.append(f"**{t('为什么重要', 'Why it matters')}：** {trend['why_matters']}")
            lines.append("")

    # Build Ideas
    ideas = report.get("build_ideas", [])
    if ideas:
        lines.append(f"## {t('2 小时构建点子', '2-Hour Build Ideas')}")
        lines.append("")
        for i, idea in enumerate(ideas, 1):
            lines.append(f"**{i}. {idea.get('idea', '')}**")
            if idea.get("stack"):
                lines.append(f"- {t('技术栈', 'Stack')}: {idea['stack']}")
            if idea.get("audience"):
                lines.append(f"- {t('目标用户', 'Audience')}: {idea['audience']}")
            lines.append("")

    # Questions
    questions = report.get("questions", [])
    if questions:
        lines.append(f"## {t('20 个值得思考的问题', '20 Questions Worth Asking')}")
        lines.append("")
        for i, q in enumerate(questions, 1):
            lines.append(f"{i}. {q}")
        lines.append("")

    # Sources
    sources = report.get("sources_cited", [])
    if sources:
        lines.append(f"## {t('数据源', 'Sources')}")
        lines.append("")
        for s in sources:
            title = s.get("title", "")
            url = s.get("url", "")
            source_name = s.get("source", "")
            lines.append(f"- [{title}]({url}) — _{source_name}_")
        lines.append("")

    lines.append("---")
    lines.append(f"_{t('由 DailyDawn 自动生成', 'Auto-generated by DailyDawn')} · {datetime.utcnow().isoformat()}Z_")

    return "\n".join(lines)


def save_report(markdown: str, lang: str, date: str) -> Path:
    year = date[:4]
    dir_path = ROOT / lang / year
    dir_path.mkdir(parents=True, exist_ok=True)
    file_path = dir_path / f"{date}.md"
    file_path.write_text(markdown, encoding="utf-8")
    return file_path
